version: '3.8'
services:
  shareIt-gateway:
    build: shareIt-gateway/
    image: "gateway"
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - shareIt-server
    environment:
      - SHAREIT_SERVER_URL=http://shareIt-server:9090

  shareIt-server:
    build: shareIt-server/
    image: "server"
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:16.1
    container_name: shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
